Improvements to the build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,12 +1,20 @@
-#!/bin/sh
+#!/bin/sh -e
+# Note: the '-e' flag will make the script stop immediately upon error with 
+# the error reflected in the environment.  This lets one issue commands like
+# "./build sbitx && ./sbitx" to build then run if it built correctly, and not
+# run if the build failed.
 F=$@
+[ -z "$F" ] && {
+   echo "usage:   build 'name-of-program'"
+   echo "example: build sbitx"
+   exit 1
+}
 WORKING_DIRECTORY=`pwd`
 echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
 date
-mkdir -p "/home/pi/sbitx/audio"
-mkdir -p "/home/pi/sbitx/data"
-#cd /home/pi/sbitx
-mkdir -p "/home/pi/sbitx/web"
+mkdir -p "./audio"
+mkdir -p "./data"
+mkdir -p "./web"
 
 if test -f "data/sbitx.db"; then
 	echo "database is intact"
@@ -24,11 +32,11 @@ else
   echo "compiling $F version $VERSION in $WORKING_DIRECTORY"
 fi
 gcc -g -o $F \
-	 vfo.c si570.c sbitx_sound.c fft_filter.c  sbitx_gtk.c sbitx_utils.c \
-    i2cbb.c si5351v2.c ini.c hamlib.c queue.c modems.c logbook.c \
-		modem_cw.c \
-		telnet.c macros.c modem_ft8.c remote.c mongoose.c webserver.c $F.c  \
-		ft8_lib/libft8.a  \
+	vfo.c si570.c sbitx_sound.c fft_filter.c  sbitx_gtk.c sbitx_utils.c \
+	i2cbb.c si5351v2.c ini.c hamlib.c queue.c modems.c logbook.c \
+	modem_cw.c \
+	telnet.c macros.c modem_ft8.c remote.c mongoose.c webserver.c $F.c  \
+	ft8_lib/libft8.a  \
 	-lwiringPi -lasound -lm -lfftw3 -lfftw3f -pthread -lncurses -lsqlite3\
 	`pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
 echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
